#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Execution --------------------------------

# db refreshed
#echo -e "${green_bg} Step 1 ${NC}${green} Downloading database...${NC}"
latest_db_file="gsabin-local-10-24-19.sql"
latest_db="/tmp/$latest_db_file"
# This runs inside cli using http://docs.docksal.io/en/v1.4.0/fin/custom-commands/#executing-commands-inside-cli
# scp wcirb.dev@srv-4525.devcloud.hosting.acquia.com:"$latest_db" /tmp/
echo -e "${green_bg} Making sure local servers are running..."
fin project start
echo -e "${green_bg} Step 2 ${NC}${green} Importing database...${NC}"
fin db import $latest_db --db=gena

echo -e "${green_bg} DONE! ${NC}${green} Completed all db steps.${NC}"

#-------------------------- END: Execution --------------------------------
